name             'poisesample'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures poisesample'
long_description 'Installs/Configures poisesample'
version          '0.1.0'
